#첫 빌드시 : docker-compose up --build
#이후 : docker-compose up
# 방화벽 설정으로 실행 안될때 iptables 초기화 
# sudo iptables -t filter -F && sudo iptables -t filter -X && sudo systemctl restart docker
version: "3"
services:
  oruum:
    image: joker1251/oruum-backend:2207-2
    container_name : oruum-backend
    working_dir: /home/ORUUM-REST-API
    ports: 
      - "8000:8000"
    restart: always
    command: >
      bash -c "
      && python3 manage.py makemigrations
      && python3 manage.py migrate
      && gunicorn backend.wsgi:application -b 0.0.0.0:8000"
    depends_on :
      - mysql
    volumes:
      - .:/home/ORUUM-REST-API
    links:
      - mysql
    expose:
      - 8000
   
  nginx:
    image: joker1251/oruum-nginx:2206
    container_name : oruum-nginx
    ports:
      - "80:80"
    restart: always
    volumes:
      - .:/home/ORUUM-REST-API
      - ./config/nginx:/etc/nginx/conf.d
      - ./config/certbot/conf:/etc/letsencrypt
      - ./config/certbot/www:/var/www/certbot

    depends_on : 
      - oruum
  
  certbot:
    image: certbot/certbot:v1.26.0
    container_name:  oruum-ssl
    restart: always
    volumes:
      - ./config/certbot/conf:/etc/letsencrypt
      - ./config/certbot/www:/var/www/certbot
    
  mysql:
    image: joker1251/oruum-mysql:2206
    container_name : oruum-mysql
    ports:
      - "3306:3306"
    restart: always
    volumes:
      - .:/home/ORUUM-REST-API
    environment:
      MYSQL_ROOT_PASSWORD: 3102
      MYSQL_DATABASE: oruum_db