# Generated by Django 4.0 on 2022-04-12 23:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stock_list',
            name='ticker',
            field=models.CharField(default='', help_text='Ticker(Symbol)', max_length=50, primary_key=True, serialize=False, verbose_name='ticker'),
        ),
        migrations.AlterField(
            model_name='stock_price_history',
            name='ticker',
            field=models.ForeignKey(db_column='ticker', on_delete=django.db.models.deletion.CASCADE, related_name='stock_price_history', to='api.stock_list'),
        ),
        migrations.AlterField(
            model_name='user_list',
            name='id_user',
            field=models.BigAutoField(help_text='id_user_list', primary_key=True, serialize=False),
        ),
    ]
