# Generated by Django 4.0 on 2022-04-05 15:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_stockinformation_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stockinformation',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='stockinformation',
            name='symbol',
            field=models.ForeignKey(db_column='symbol', on_delete=django.db.models.deletion.CASCADE, related_name='stock', to='api.stockprice', unique=True),
        ),
    ]
