# Generated by Django 4.0 on 2022-04-05 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_stockinformation_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stockinformation',
            name='id',
            field=models.BigAutoField(help_text='StockInformation id as pk', primary_key=True, serialize=False),
        ),
    ]
