# Generated by Django 4.0 on 2022-04-05 15:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_remove_stockinformation_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stockinformation',
            name='symbol',
            field=models.OneToOneField(db_column='symbol', on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='stockinformation', serialize=False, to='api.stockprice'),
        ),
    ]
