# Generated by Django 4.0 on 2022-04-06 03:34

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_stockhistory'),
    ]

    operations = [
        migrations.AddField(
            model_name='stockinformation',
            name='date',
            field=models.DateField(default=datetime.datetime.today, help_text='날짜', verbose_name='date'),
        ),
        migrations.AddField(
            model_name='stockprice',
            name='date',
            field=models.DateField(default=datetime.datetime.today, help_text='날짜', verbose_name='date'),
        ),
        migrations.AlterField(
            model_name='stockhistory',
            name='date',
            field=models.DateField(default=datetime.datetime.today, help_text='날짜', verbose_name='date'),
        ),
    ]
