# Generated by Django 4.0 on 2022-04-06 03:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_stockinformation_date_stockprice_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stockhistory',
            name='dividends',
            field=models.FloatField(blank=True, help_text='배당 내역', null=True, verbose_name='dividends'),
        ),
        migrations.AlterField(
            model_name='stockhistory',
            name='splits',
            field=models.FloatField(blank=True, help_text='주식분할 내역', null=True, verbose_name='spits'),
        ),
    ]
