# Generated by Django 4.0 on 2022-04-06 04:56

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_alter_stockhistory_dividends_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='StockHistory_AAPL',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=datetime.datetime.today, help_text='날짜', unique=True, verbose_name='date')),
                ('update_dt', models.DateTimeField(auto_now=True, verbose_name='update_dt')),
                ('create_dt', models.DateTimeField(auto_now_add=True, verbose_name='create_dt')),
                ('splits', models.FloatField(blank=True, help_text='주식분할 내역', null=True, verbose_name='spits')),
                ('dividends', models.FloatField(blank=True, help_text='배당 내역', null=True, verbose_name='dividends')),
                ('opens', models.FloatField(default=0, help_text='개장가', verbose_name='opens')),
                ('high', models.FloatField(default=0, help_text='고가', verbose_name='opens')),
                ('low', models.FloatField(default=0, help_text='저가', verbose_name='opens')),
                ('close', models.FloatField(default=0, help_text='종가', verbose_name='opens')),
                ('adj_close', models.FloatField(default=0, help_text='조정 종가', verbose_name='opens')),
                ('volume', models.FloatField(default=0, help_text='거래량', verbose_name='opens')),
                ('symbol', models.ForeignKey(db_column='symbol', on_delete=django.db.models.deletion.CASCADE, related_name='stockhistory_AAPL', to='api.stockprice')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='StockHistory_MSFT',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=datetime.datetime.today, help_text='날짜', unique=True, verbose_name='date')),
                ('update_dt', models.DateTimeField(auto_now=True, verbose_name='update_dt')),
                ('create_dt', models.DateTimeField(auto_now_add=True, verbose_name='create_dt')),
                ('splits', models.FloatField(blank=True, help_text='주식분할 내역', null=True, verbose_name='spits')),
                ('dividends', models.FloatField(blank=True, help_text='배당 내역', null=True, verbose_name='dividends')),
                ('opens', models.FloatField(default=0, help_text='개장가', verbose_name='opens')),
                ('high', models.FloatField(default=0, help_text='고가', verbose_name='opens')),
                ('low', models.FloatField(default=0, help_text='저가', verbose_name='opens')),
                ('close', models.FloatField(default=0, help_text='종가', verbose_name='opens')),
                ('adj_close', models.FloatField(default=0, help_text='조정 종가', verbose_name='opens')),
                ('volume', models.FloatField(default=0, help_text='거래량', verbose_name='opens')),
                ('symbol', models.ForeignKey(db_column='symbol', on_delete=django.db.models.deletion.CASCADE, related_name='stockhistory_MSFT', to='api.stockprice')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='StockHistory_NVDA',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=datetime.datetime.today, help_text='날짜', unique=True, verbose_name='date')),
                ('update_dt', models.DateTimeField(auto_now=True, verbose_name='update_dt')),
                ('create_dt', models.DateTimeField(auto_now_add=True, verbose_name='create_dt')),
                ('splits', models.FloatField(blank=True, help_text='주식분할 내역', null=True, verbose_name='spits')),
                ('dividends', models.FloatField(blank=True, help_text='배당 내역', null=True, verbose_name='dividends')),
                ('opens', models.FloatField(default=0, help_text='개장가', verbose_name='opens')),
                ('high', models.FloatField(default=0, help_text='고가', verbose_name='opens')),
                ('low', models.FloatField(default=0, help_text='저가', verbose_name='opens')),
                ('close', models.FloatField(default=0, help_text='종가', verbose_name='opens')),
                ('adj_close', models.FloatField(default=0, help_text='조정 종가', verbose_name='opens')),
                ('volume', models.FloatField(default=0, help_text='거래량', verbose_name='opens')),
                ('symbol', models.ForeignKey(db_column='symbol', on_delete=django.db.models.deletion.CASCADE, related_name='stockhistory_NVDA', to='api.stockprice')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='StockHistory_TSLA',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=datetime.datetime.today, help_text='날짜', unique=True, verbose_name='date')),
                ('update_dt', models.DateTimeField(auto_now=True, verbose_name='update_dt')),
                ('create_dt', models.DateTimeField(auto_now_add=True, verbose_name='create_dt')),
                ('splits', models.FloatField(blank=True, help_text='주식분할 내역', null=True, verbose_name='spits')),
                ('dividends', models.FloatField(blank=True, help_text='배당 내역', null=True, verbose_name='dividends')),
                ('opens', models.FloatField(default=0, help_text='개장가', verbose_name='opens')),
                ('high', models.FloatField(default=0, help_text='고가', verbose_name='opens')),
                ('low', models.FloatField(default=0, help_text='저가', verbose_name='opens')),
                ('close', models.FloatField(default=0, help_text='종가', verbose_name='opens')),
                ('adj_close', models.FloatField(default=0, help_text='조정 종가', verbose_name='opens')),
                ('volume', models.FloatField(default=0, help_text='거래량', verbose_name='opens')),
                ('symbol', models.ForeignKey(db_column='symbol', on_delete=django.db.models.deletion.CASCADE, related_name='stockhistory_TSLA', to='api.stockprice')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.DeleteModel(
            name='StockHistory',
        ),
    ]
