# Generated by Django 4.0 on 2022-04-06 12:56

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_stockhistory_remove_stockhistory_msft_symbol_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stockhistory',
            name='date',
            field=models.DateField(default=datetime.datetime.today, help_text='날짜', verbose_name='date'),
        ),
    ]
